[project]
name = "traffic-route-monitor"
version = "0.1.0"
description = "Traffic route monitoring system"
requires-python = ">=3.8"
dependencies = [
    "psycopg2-binary",
    "requests",
    "schedule"
]

[project.scripts]
test = "test:run_all_tests"
